ALTER TABLE EMP1 ADD (
    Skills VARCHAR2(10),
    DOB DATE
);
UPDATE EMP1
 SET Skills = 'SQL',
  DOB = TO_DATE('2023-06-15','YYYY-MM-DD')
WHERE ID = 1;

UPDATE EMP1
 SET Skills = 'Java',
  DOB = TO_DATE('2023-02-10','YYYY-MM-DD')
WHERE ID = 2;

UPDATE EMP1 
SET Skills = 'Python',
 DOB = TO_DATE('2023-09-11','YYYY-MM-DD')
WHERE ID = 3;

UPDATE EMP1 
SET Skills = 'DBMS',
 DOB = TO_DATE('2024-06-06','YYYY-MM-DD')
WHERE ID = 4;

UPDATE EMP1 
SET Skills = 'C', 
DOB = TO_DATE('2024-05-12','YYYY-MM-DD')
WHERE ID = 5;

UPDATE EMP1
 SET Skills = 'C++',
  DOB = TO_DATE('2022-10-10','YYYY-MM-DD')
WHERE ID = 6;
COMMIT;
SELECT * FROM EMP1;    